### ISSUE TITLE
Show error if user starts city with incorrect parameters

### ISSUE THREAD

**Issue by feeeper** [raelmax/city#6]
Start city without `-config=`: 
`city.exe config.yaml -port=9091 -timeout=5`
App starts but not working and shows "This web page is not available" message when I open http://localhost:9091.

As I can see if I remove `-config=` then app listening default port:
![default](https://cloud.githubusercontent.com/assets/3373303/19179612/6e92c464-8c70-11e6-80e6-24b42e1942f8.PNG)

I think that it will be better show some message about invalid parameters.

**Comment by raelmax** [comment]
Currently we use the Flag package of golang's standard library. I think that's great to improve the parse with better messages and error checking. Can you help with this issue? :)

**Comment by feeeper** [comment]
Yes, sure. Can you add some labels for the issue? :)
